language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"

env:
  - TASK=default

matrix:
  include:
    - node_js: "7"
      env: TASK=travis-phantomjs

install:
  - npm install
  - npm install -g nodeunit grunt-cli
  - if [ $TASK = travis-phantomjs ]; then npm install -g browserify uglify-js; fi

script:
  - grunt $TASK

sudo: required
dist: trusty

notifications:
  slack: cocolab-stanford:X2Ebs0qIMVUidJBD1xZd2XU1
